// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // Current setup is using web config even for mobile if not configured
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyA-2aHswGGpbN4dL2Q7oFWjyv5TEiz5d7M",
    authDomain: "bellavella-68c59.firebaseapp.com",
    projectId: "bellavella-68c59",
    storageBucket: "bellavella-68c59.firebasestorage.app",
    messagingSenderId: "639709879636",
    appId: "1:639709879636:web:7030ca092280a6c6d23cc1",
    measurementId: "G-BF9BPY0047",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyA-2aHswGGpbN4dL2Q7oFWjyv5TEiz5d7M",
    appId: "1:639709879636:android:7030ca092280a6c6d23cc1", // Typical mapping
    messagingSenderId: "639709879636",
    projectId: "bellavella-68c59",
    storageBucket: "bellavella-68c59.firebasestorage.app",
  );
}
